// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PAR.Infrastructure.Persistence;

#nullable disable

namespace PAR.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260403234733_AddMenusAndPermissions")]
    partial class AddMenusAndPermissions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PAR.Domain.Entities.LoginAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<DateTime>("AttemptedAt").HasColumnType("datetime2");
                    b.Property<string>("FailureReason").HasColumnType("nvarchar(max)");
                    b.Property<string>("IpAddress").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.Property<bool>("Success").HasColumnType("bit");
                    b.Property<int?>("UserId").HasColumnType("int");
                    b.Property<string>("Username").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.HasKey("Id");
                    b.HasIndex("UserId");
                    b.HasIndex("IpAddress", "AttemptedAt");
                    b.HasIndex("Username", "AttemptedAt");
                    b.ToTable("LoginAttempts", (string)null);
                });

            modelBuilder.Entity("PAR.Domain.Entities.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("Icon").HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.Property<bool>("IsActive").HasColumnType("bit");
                    b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.Property<int>("Order").HasColumnType("int");
                    b.HasKey("Id");
                    b.ToTable("Menus", (string)null);
                    b.HasData(
                        new { Id = 1, Icon = "admin",  IsActive = true, Name = "Administración", Order = 1 },
                        new { Id = 2, Icon = "config", IsActive = true, Name = "Configuración",  Order = 2 });
                });

            modelBuilder.Entity("PAR.Domain.Entities.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("Icon").HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.Property<bool>("IsActive").HasColumnType("bit");
                    b.Property<int>("MenuId").HasColumnType("int");
                    b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.Property<int>("Order").HasColumnType("int");
                    b.Property<string>("RequiredPermission").HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.Property<string>("Route").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                    b.HasKey("Id");
                    b.HasIndex("MenuId");
                    b.ToTable("MenuItems", (string)null);
                    b.HasData(
                        new { Id = 1, Icon = "people", IsActive = true, MenuId = 1, Name = "Usuarios",           Order = 1, RequiredPermission = "users.read",        Route = "/admin/users"             },
                        new { Id = 2, Icon = "key",    IsActive = true, MenuId = 2, Name = "Usuario y Permisos",  Order = 1, RequiredPermission = "users.permissions", Route = "/config/user-permissions" });
                });

            modelBuilder.Entity("PAR.Domain.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("Description").HasColumnType("nvarchar(max)");
                    b.Property<string>("Module").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.HasKey("Id");
                    b.ToTable("Permissions", (string)null);
                    b.HasData(
                        new { Id = 1, Description = "View users",                       Module = "Users",  Name = "users.read" },
                        new { Id = 2, Description = "Create users",                      Module = "Users",  Name = "users.create" },
                        new { Id = 3, Description = "Update users",                      Module = "Users",  Name = "users.update" },
                        new { Id = 4, Description = "Delete users",                      Module = "Users",  Name = "users.delete" },
                        new { Id = 5, Description = "Lock/unlock users",                 Module = "Users",  Name = "users.lock" },
                        new { Id = 6, Description = "Manage user roles and permissions", Module = "Config", Name = "users.permissions" });
                });

            modelBuilder.Entity("PAR.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("Description").HasColumnType("nvarchar(max)");
                    b.Property<bool>("IsActive").HasColumnType("bit");
                    b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.HasKey("Id");
                    b.ToTable("Roles", (string)null);
                    b.HasData(
                        new { Id = 1, Description = "Administrator", IsActive = true, Name = "Admin" },
                        new { Id = 2, Description = "Standard user", IsActive = true, Name = "User" });
                });

            modelBuilder.Entity("PAR.Domain.Entities.RolePermission", b =>
                {
                    b.Property<int>("RoleId").HasColumnType("int");
                    b.Property<int>("PermissionId").HasColumnType("int");
                    b.HasKey("RoleId", "PermissionId");
                    b.HasIndex("PermissionId");
                    b.ToTable("RolePermissions", (string)null);
                    b.HasData(
                        new { RoleId = 1, PermissionId = 1 },
                        new { RoleId = 1, PermissionId = 2 },
                        new { RoleId = 1, PermissionId = 3 },
                        new { RoleId = 1, PermissionId = 4 },
                        new { RoleId = 1, PermissionId = 5 },
                        new { RoleId = 1, PermissionId = 6 },
                        new { RoleId = 2, PermissionId = 1 });
                });

            modelBuilder.Entity("PAR.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<string>("Email").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                    b.Property<string>("FirstName").HasColumnType("nvarchar(max)");
                    b.Property<bool>("IsActive").HasColumnType("bit");
                    b.Property<bool>("IsLocked").HasColumnType("bit");
                    b.Property<string>("LastName").HasColumnType("nvarchar(max)");
                    b.Property<string>("PasswordHash").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
                    b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
                    b.Property<string>("Username").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.HasKey("Id");
                    b.HasIndex("Email").IsUnique();
                    b.HasIndex("Username").IsUnique();
                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("PAR.Domain.Entities.UserPasswordHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<string>("PasswordHash").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<int>("UserId").HasColumnType("int");
                    b.HasKey("Id");
                    b.HasIndex("UserId");
                    b.ToTable("UserPasswordHistories", (string)null);
                });

            modelBuilder.Entity("PAR.Domain.Entities.UserRole", b =>
                {
                    b.Property<int>("UserId").HasColumnType("int");
                    b.Property<int>("RoleId").HasColumnType("int");
                    b.HasKey("UserId", "RoleId");
                    b.HasIndex("RoleId");
                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("PAR.Domain.Entities.LoginAttempt", b =>
                {
                    b.HasOne("PAR.Domain.Entities.User", "User").WithMany("LoginAttempts").HasForeignKey("UserId");
                    b.Navigation("User");
                });

            modelBuilder.Entity("PAR.Domain.Entities.MenuItem", b =>
                {
                    b.HasOne("PAR.Domain.Entities.Menu", "Menu")
                        .WithMany("Items")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Menu");
                });

            modelBuilder.Entity("PAR.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("PAR.Domain.Entities.Permission", "Permission").WithMany("RolePermissions").HasForeignKey("PermissionId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("PAR.Domain.Entities.Role", "Role").WithMany("RolePermissions").HasForeignKey("RoleId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Permission");
                    b.Navigation("Role");
                });

            modelBuilder.Entity("PAR.Domain.Entities.UserPasswordHistory", b =>
                {
                    b.HasOne("PAR.Domain.Entities.User", "User").WithMany("PasswordHistories").HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("User");
                });

            modelBuilder.Entity("PAR.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("PAR.Domain.Entities.Role", "Role").WithMany("UserRoles").HasForeignKey("RoleId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("PAR.Domain.Entities.User", "User").WithMany("UserRoles").HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Role");
                    b.Navigation("User");
                });

            modelBuilder.Entity("PAR.Domain.Entities.Menu", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("PAR.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("PAR.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("PAR.Domain.Entities.User", b =>
                {
                    b.Navigation("LoginAttempts");
                    b.Navigation("PasswordHistories");
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
